//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Watersan_e_Firejalma.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Maps {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Maps() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Watersan_e_Firejalma.Properties.Maps", typeof(Maps).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a v v v v v v v v v v v v v a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a
        ///v v v v v v v v v v v v v a a a a a g h a a a a a a i a a a a g h a a a a a a g h a a a a a
        ///v v v v v v v v v v v v v a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a
        ///v v v v v v v v v v v v v a d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d a
        ///a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a
        ///a a a a a a a a a a a a a a a a a a a a a a a a [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string fundoMapa0 {
            get {
                return ResourceManager.GetString("fundoMapa0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a
        ///a a g h a a a a i a a a a a a a g h a a a a a a a a g h a a a a a a a a a a a a
        ///a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a
        ///a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a
        ///d d d d d d d d d d d d d d d d d d d d d f d d d d d d d d d d d d d f d d d d
        ///a a a a a a a a a a a a a a a a j a j a j a a a a a a a a a a a a a a a a a a a
        ///a a a a a a a a a a a a a  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string fundoMapa1 {
            get {
                return ResourceManager.GetString("fundoMapa1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a
        ///a a a a a a g h a a a a a a a a a a a a a a a a g h a a a a a a a a a a a a a a
        ///a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a
        ///a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a
        ///a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a
        ///d d d d d d d d f d d d d d d d f d d d d d d f d d d d d d d d d f d d d d d d
        ///a a a a a a a j a a a k a  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string fundoMapa2 {
            get {
                return ResourceManager.GetString("fundoMapa2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a
        ///a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a
        ///&lt;&lt;&lt;&lt;&lt;&lt;&lt; HEAD
        ///d f d d d d a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a
        ///a a a a a d d d d d d d d f d d d d d d d d f d d d d d d d d d d f d d d d d
        ///a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a
        ///a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a
        ///d d d d f d d d d d a a  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string fundoMapa3 {
            get {
                return ResourceManager.GetString("fundoMapa3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a v v v v v v v v v v v v v a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a
        ///v v v v v v v v v v v v v a v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v a
        ///v v v v v v v v v v v v v a v v v v v v v v v r v v v v v v v v v v v r v v v v v v v v v a
        ///v v v v v v v v v v v v v a v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v a
        ///a a a a a a a a a a a a a a v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v a
        ///a v v v v v v v v v v v v v v v v v v v v v v v [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string MapaFase0 {
            get {
                return ResourceManager.GetString("MapaFase0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a
        ///a v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v a
        ///a v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v a
        ///a v v v v v v v v v v q v v v v v v v v v v v v v v v v v v v v v v v v v v v a
        ///a v v v v v v v v a a a a a v v v v v v v v v v v v v v v v v v v v s v t v v a
        ///a v v v v v v v v v a a a a a v v v v v v v r v v v a a a a a v v v v v v v v a
        ///a v v r v v v v v v v a a  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string MapaFase1 {
            get {
                return ResourceManager.GetString("MapaFase1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a
        ///a v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v a
        ///a v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v a
        ///a v v v v v v v v v v v v v v v v v v q v r v v v v v v v v v v v v v v v v v a
        ///a v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v a
        ///a v s v t v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v a
        ///a v v v v v v v v v v v v  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string MapaFase2 {
            get {
                return ResourceManager.GetString("MapaFase2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a
        ///a a v v v a a a a v v v v v v v v v v v v v v v v v v v v v v v v v v v v v a
        ///a v v v v v a a v v v v v v v v q v v v v v q v v v v v q v v v v v v v v v a
        ///a a v v v a a v v v v v v v v v v v v v v v v v v v v v v v v v v v v o v v a
        ///a a a a a a v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v a a
        ///a a v v v v v v v a a a a v v v v v v v v v v v v v v v v v v v v a a a a a a
        ///a v v v v q v v a a a a a a a v v v v  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string MapaFase3 {
            get {
                return ResourceManager.GetString("MapaFase3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap senairio {
            get {
                object obj = ResourceManager.GetObject("senairio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Senairio2_0 {
            get {
                object obj = ResourceManager.GetObject("Senairio2_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SenairiodeFundo2_0 {
            get {
                object obj = ResourceManager.GetObject("SenairiodeFundo2_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SenairiodeFundoGame2_0 {
            get {
                object obj = ResourceManager.GetObject("SenairiodeFundoGame2_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
